# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data/gui/dialog_edit_web.ui'
#
# Created: Sun Jan  4 23:03:19 2015
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DialogAddWeb(object):
    def setupUi(self, DialogAddWeb):
        DialogAddWeb.setObjectName(_fromUtf8("DialogAddWeb"))
        DialogAddWeb.resize(608, 411)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(DialogAddWeb.sizePolicy().hasHeightForWidth())
        DialogAddWeb.setSizePolicy(sizePolicy)
        DialogAddWeb.setModal(True)
        self.verticalLayout = QtGui.QVBoxLayout(DialogAddWeb)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(DialogAddWeb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setCheckable(False)
        self.groupBox_2.setChecked(False)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setSizeConstraint(QtGui.QLayout.SetMinAndMaxSize)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_7 = QtGui.QLabel(self.groupBox_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_7)
        self.e_title = QtGui.QLineEdit(self.groupBox_2)
        self.e_title.setObjectName(_fromUtf8("e_title"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.e_title)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_8)
        self.e_url = QtGui.QLineEdit(self.groupBox_2)
        self.e_url.setObjectName(_fromUtf8("e_url"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.e_url)
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_9)
        self.e_interval = QtGui.QSpinBox(self.groupBox_2)
        self.e_interval.setMaximum(50000)
        self.e_interval.setSingleStep(5)
        self.e_interval.setObjectName(_fromUtf8("e_interval"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.e_interval)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_10)
        self.c_group = QtGui.QComboBox(self.groupBox_2)
        self.c_group.setObjectName(_fromUtf8("c_group"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.c_group)
        self.horizontalLayout_2.addLayout(self.formLayout_2)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(DialogAddWeb)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetMinimumSize)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.rb_scan_parts = QtGui.QRadioButton(self.groupBox)
        self.rb_scan_parts.setObjectName(_fromUtf8("rb_scan_parts"))
        self.gridLayout_2.addWidget(self.rb_scan_parts, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.rb_scan_page = QtGui.QRadioButton(self.groupBox)
        self.rb_scan_page.setChecked(True)
        self.rb_scan_page.setObjectName(_fromUtf8("rb_scan_page"))
        self.gridLayout_2.addWidget(self.rb_scan_page, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 1, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 3, 1, 1, 1)
        self.e_xpath = QtGui.QPlainTextEdit(self.groupBox)
        self.e_xpath.setObjectName(_fromUtf8("e_xpath"))
        self.gridLayout_2.addWidget(self.e_xpath, 3, 2, 1, 1)
        self.sb_similarity_ratio = QtGui.QDoubleSpinBox(self.groupBox)
        self.sb_similarity_ratio.setMaximum(100.0)
        self.sb_similarity_ratio.setObjectName(_fromUtf8("sb_similarity_ratio"))
        self.gridLayout_2.addWidget(self.sb_similarity_ratio, 1, 2, 1, 1)
        self.gridLayout_2.setColumnStretch(2, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.cancel_btn = QtGui.QPushButton(DialogAddWeb)
        self.cancel_btn.setObjectName(_fromUtf8("cancel_btn"))
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.add_btn = QtGui.QPushButton(DialogAddWeb)
        self.add_btn.setDefault(True)
        self.add_btn.setObjectName(_fromUtf8("add_btn"))
        self.horizontalLayout.addWidget(self.add_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DialogAddWeb)
        QtCore.QObject.connect(self.rb_scan_page, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.sb_similarity_ratio.setEnabled)
        QtCore.QObject.connect(self.rb_scan_parts, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.e_xpath.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(DialogAddWeb)

    def retranslateUi(self, DialogAddWeb):
        DialogAddWeb.setWindowTitle(_translate("DialogAddWeb", "Add Web Page", None))
        self.groupBox_2.setTitle(_translate("DialogAddWeb", "Main", None))
        self.label_7.setText(_translate("DialogAddWeb", "Title:", None))
        self.label_8.setText(_translate("DialogAddWeb", "URL:", None))
        self.label_9.setText(_translate("DialogAddWeb", "<html><head/><body><p>Update  interval [min]:</p></body></html>", None))
        self.label_10.setText(_translate("DialogAddWeb", "Group:", None))
        self.groupBox.setTitle(_translate("DialogAddWeb", "Options", None))
        self.rb_scan_parts.setText(_translate("DialogAddWeb", "Find page parts", None))
        self.rb_scan_page.setText(_translate("DialogAddWeb", "Scan whole page", None))
        self.label_6.setText(_translate("DialogAddWeb", "Ignored changes level: ", None))
        self.label_4.setText(_translate("DialogAddWeb", "XPath:", None))
        self.cancel_btn.setText(_translate("DialogAddWeb", "Close", None))
        self.add_btn.setText(_translate("DialogAddWeb", "Add", None))

